name: licenseGenerator
on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 1 1 * *'

jobs:
  run:
    name: Generate License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Generate License
        uses: yi-Xu-0100/license-generator@v0.1.0
        with:
          path: /
          type: MIT
          year: 2024
          author: Joshua Ross
